let allQuestions=[];let questions=[];let currentIndex=0;let selectedAnswers={};let checkedQuestions={};
const $=id=>document.getElementById(id);
const quizTitle=$('quiz-title'),quizSubtitle=$('quiz-subtitle'),score=$('score'),domainFilter=$('domain-filter'),topicFilter=$('topic-filter'),shuffleBtn=$('shuffle-btn'),resetBtn=$('reset-btn'),questionCounter=$('question-counter'),questionId=$('question-id'),progressFill=$('progress-fill'),domainBadge=$('domain-badge'),topicBadge=$('topic-badge'),statement=$('statement'),questionText=$('question-text'),optionsContainer=$('options-container'),feedback=$('feedback'),prevBtn=$('prev-btn'),checkBtn=$('check-btn'),nextBtn=$('next-btn'),totalAnswered=$('total-answered'),totalCorrect=$('total-correct'),totalWrong=$('total-wrong'),accuracy=$('accuracy');

async function init(){try{const res=await fetch('data/preguntas.json');if(!res.ok)throw new Error('No se pudo cargar data/preguntas.json');const data=await res.json();allQuestions=Array.isArray(data.preguntas)?data.preguntas:[];questions=[...allQuestions];quizTitle.textContent=data.metadata?.titulo||'Banco de preguntas';quizSubtitle.textContent=`${questions.length} preguntas disponibles`;fillFilters();renderQuestion()}catch(e){document.body.innerHTML=`<main class="app"><section class="question-card"><h1>Error cargando el JSON</h1><p>No se ha podido cargar <strong>data/preguntas.json</strong>.</p><p>Revisa que el archivo exista, que el JSON sea válido y que estés ejecutando la app desde un servidor local.</p><pre>${escapeHTML(e.message)}</pre></section></main>`}}

function fillFilters(){fillSelect(domainFilter,unique(allQuestions,'dominio'),'Todos');fillSelect(topicFilter,unique(allQuestions,'tema'),'Todos')}
function fillSelect(select,values,txt){select.innerHTML='';const op=document.createElement('option');op.value='all';op.textContent=txt;select.appendChild(op);values.forEach(v=>{if(!v)return;const o=document.createElement('option');o.value=v;o.textContent=v;select.appendChild(o)})}
function unique(items,key){return[...new Set(items.map(i=>i[key]).filter(Boolean))].sort()}

function renderQuestion(){if(!questions.length){renderEmptyState();updateStats();return}const q=questions[currentIndex];const selected=selectedAnswers[q.id];const checked=checkedQuestions[q.id];questionCounter.textContent=`Pregunta ${currentIndex+1} de ${questions.length}`;questionId.textContent=q.id||`#${q.numero}`;progressFill.style.width=`${((currentIndex+1)/questions.length)*100}%`;domainBadge.textContent=q.dominio||'Sin dominio';topicBadge.textContent=q.tema||'Sin tema';statement.textContent=q.enunciado||'';questionText.textContent=q.pregunta||'Pregunta sin texto';optionsContainer.innerHTML='';Object.entries(q.opciones||{}).forEach(([letter,text])=>{const label=document.createElement('label');label.className='option';if(selected===letter)label.classList.add('selected');if(checked){if(letter===q.respuesta_correcta)label.classList.add('correct');if(letter===selected&&letter!==q.respuesta_correcta)label.classList.add('incorrect')}const input=document.createElement('input');input.type='radio';input.name='answer';input.value=letter;input.checked=selected===letter;input.disabled=Boolean(checked);const letterSpan=document.createElement('span');letterSpan.className='option-letter';letterSpan.textContent=letter;const textSpan=document.createElement('span');textSpan.textContent=text;label.append(input,letterSpan,textSpan);label.addEventListener('click',()=>{if(checkedQuestions[q.id])return;selectedAnswers[q.id]=letter;renderQuestion()});optionsContainer.appendChild(label)});renderFeedback(q);updateButtons();updateStats()}

function renderFeedback(q){const checked=checkedQuestions[q.id];if(!checked){feedback.className='feedback hidden';feedback.innerHTML='';return}const selected=selectedAnswers[q.id];const ok=selected===q.respuesta_correcta;feedback.className=`feedback ${ok?'correct':'incorrect'}`;feedback.innerHTML=`<strong>${ok?'Correcto':'Incorrecto'}</strong><p>Respuesta correcta: <strong>${escapeHTML(q.respuesta_correcta)}</strong></p><p>${escapeHTML(q.explicacion||'No hay explicación disponible.')}</p>`}
function updateButtons(){prevBtn.disabled=currentIndex===0;nextBtn.disabled=currentIndex===questions.length-1;const q=questions[currentIndex];const checked=checkedQuestions[q.id];checkBtn.disabled=Boolean(checked);checkBtn.textContent=checked?'Comprobada':'Comprobar'}
function updateStats(){const ids=Object.keys(checkedQuestions);const correct=ids.filter(id=>checkedQuestions[id].isCorrect).length;const wrong=ids.length-correct;const pct=ids.length===0?0:Math.round(correct/ids.length*100);score.textContent=`${correct} / ${ids.length}`;totalAnswered.textContent=ids.length;totalCorrect.textContent=correct;totalWrong.textContent=wrong;accuracy.textContent=`${pct}%`}
function checkAnswer(){const q=questions[currentIndex];const selected=selectedAnswers[q.id];if(!selected){alert('Selecciona una respuesta antes de comprobar.');return}checkedQuestions[q.id]={selected,correctAnswer:q.respuesta_correcta,isCorrect:selected===q.respuesta_correcta};renderQuestion()}
function nextQuestion(){if(currentIndex<questions.length-1){currentIndex++;renderQuestion()}}
function prevQuestion(){if(currentIndex>0){currentIndex--;renderQuestion()}}
function resetQuiz(){currentIndex=0;selectedAnswers={};checkedQuestions={};renderQuestion()}
function shuffleQuestions(){questions=[...questions].sort(()=>Math.random()-0.5);currentIndex=0;selectedAnswers={};checkedQuestions={};renderQuestion()}
function applyFilters(){const d=domainFilter.value,t=topicFilter.value;questions=allQuestions.filter(q=>(d==='all'||q.dominio===d)&&(t==='all'||q.tema===t));currentIndex=0;selectedAnswers={};checkedQuestions={};renderQuestion()}
function renderEmptyState(){questionCounter.textContent='No hay preguntas';questionId.textContent='';progressFill.style.width='0%';domainBadge.textContent='';topicBadge.textContent='';statement.textContent='';questionText.textContent='No hay preguntas disponibles para este filtro.';optionsContainer.innerHTML='';feedback.className='feedback hidden';prevBtn.disabled=true;nextBtn.disabled=true;checkBtn.disabled=true}
function escapeHTML(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
checkBtn.addEventListener('click',checkAnswer);nextBtn.addEventListener('click',nextQuestion);prevBtn.addEventListener('click',prevQuestion);resetBtn.addEventListener('click',resetQuiz);shuffleBtn.addEventListener('click',shuffleQuestions);domainFilter.addEventListener('change',applyFilters);topicFilter.addEventListener('change',applyFilters);init();
